package fluidplacer;

import cpw.mods.fml.common.ModMetadata;

public class ModData {
	
	//Metadata
	public static final String ID = "fluidplacer";
	public static final String NAME = "Fluid Placer";
	public static final String VERSION = "@FP_VERSION@";
    public static final String DEPENDENCIES = "required-after:Forge@[10.13.0.1180,);";
	
	public static void setMetadata(ModMetadata data)
	{
		data.autogenerated = false;		
		data.url = "???";
		data.credits = "";
		data.authorList.add("Matthias Mann");
		data.description = "I just want to place a fluid in the world";
		data.logoFile = "";
		data.updateUrl = "";
		data.parent = "";
	}
	
	public static final String TEXTURE_LOCATION = ID;
	
	public static final String FLUID_PLACER_KEY = "fluid_placer";
	public static final String FLUID_PLACER_UNLOCALIZED_NAME = "fluid_placer";
	
}